//
//  TLRko.swift
//  Project_Timer
//
//  Created by Kang Minsang on 2023/12/10.
//  Copyright © 2023 FDEE. All rights reserved.
//

import Foundation

struct TLRko {
    static func value(key: TLRkey, op: String? = nil) -> String {
        var value: String = ""
        switch key {
        case .Common_Text_OK: value = "확인"
        case .Common_Text_Cencel: value = "취소"
        case .Common_Text_Edit: value = "편집"
        case .Common_Text_Done: value = "완료"
        case .Common_Text_Next: value = "다음"
        case .Common_Text_Close: value = "닫기"
        case .Common_Text_Delete: value = "삭제"
        case .Common_Text_Back: value = "뒤로"
        case .Common_Text_Add: value = "추가"
        case .Common_Text_Timer: value = "타이머"
        case .Common_Text_Stopwatch: value = "스톱워치"
        case .Common_Text_TargetTime: value = "목표 시간"
        case .Common_Popup_SetMonthTargetTime: value = "Month의 목표 시간을 입력해주세요 (시간 단위)"
        case .Common_Popup_SetWeekTargetTime: value = "Week의 목표 시간을 입력해주세요 (시간 단위)"
        case .Common_Popup_SetDailyTargetTime: value = "Daily의 목표 시간을 입력해주세요 (시간 단위)"
        case .Common_Popup_SaveCompleted: value = "저장 완료"
        case .Common_Popup_Warning: value = "경고"
        case .Common_Popup_Inform: value = "안내"
            
        case .App_Popup_FetchVersionErrorTitle: value = "최신버전 정보를 불러오지 못했어요"
        case .App_Popup_FetchVersionErrorDesc: value = "문제가 계속될 경우 문의 부탁드려요."
            
        case .System_Noti_StopwatchHourPassed: value = "{}시간 경과되었습니다."
        case .System_Noti_TimerFinished: value = "타이머가 종료되었습니다!"
        case .System_Noti_Timer5Left: value = "5분 남았습니다"
        case .System_Noti_RecordingStart: value = "기록이 시작되었습니다"
            
        case .Update_Popup_HardUpdateTitle: value = "업데이트가 필요해요"
        case .Update_Popup_HardUpdateDesc: value = "최신버전으로 업데이트 해주세요"
        case .Update_Pupup_SoftUpdateTitle: value = "새로운 업데이트 알림"
        case .Update_Popup_SoftUpdateDesc: value = "{} 버전을 사용해보세요 :)"
        case .Update_Popup_Update: value = "업데이트"
        case .Update_Popup_NotNow: value = "나중에"
            
        case .Settings_Text_ProfileSection: value = "프로필"
        case .Settings_Button_SingInOption: value = "로그인하기"
        case .Settings_Button_SingInOptionDesc: value = "동기화 기능을 사용해보세요"
        case .Settings_Text_ServiceSection: value = "서비스"
        case .Settings_Button_Functions: value = "TiTi 기능들"
        case .Settings_Button_TiTiLab: value = "TiTi 연구소"
        case .Settings_Text_SettingSection: value = "설정"
        case .Settings_Button_Notification: value = "알림"
        case .Settings_Button_UI: value = "UI"
        case .Settings_Button_Control: value = "제어"
        case .Settings_Button_LanguageOption: value = "언어"
        case .Settings_Button_Widget: value = "위젯"
        case .Settings_Text_VersionSection: value = "버전 및 업데이트 내역"
        case .Settings_Button_VersionInfoTitle: value = "버전 정보"
        case .Settings_Button_VersionInfoDesc: value = "최신 버전"
        case .Settings_Button_UpdateHistory: value = "업데이트 내역"
        case .Settings_Text_BackupSection: value = "백업"
        case .Settings_Button_GetBackup: value = "백업 파일 추출"
        case .Settings_Text_DeveloperSection: value = "개발팀"
            
        case .TiTiLab_Text_DevelopNews: value = "개발 소식"
        case .TiTiLab_Button_InstagramDesc: value = "인스타그램을 통해 다양한 개발 소식을 확인해보세요"
        case .TiTiLab_Text_PartInDev: value = "개발 참여"
        case .TiTiLab_Text_SurveyTitle: value = "설문조사"
        case .TiTiLab_Text_SurveyDesc: value = "실시간으로 새로운 설문조사들이 표시됩니다.\n새로운 기능 개발 및 개선에 참여해보세요"
        case .TiTiLab_Text_NoServey: value = "현재 진행중인 설문조사가 없습니다."
        case .TiTiLab_Text_Sync: value = "동기화"
        case .TiTiLab_Button_SignUpTitle: value = "회원가입"
        case .TiTiLab_Button_SignUpDesc: value = "Dailys 기록 동기화 (beta)"
        case .TiTiLab_Button_SignIn: value = "로그인"
        case .TiTiLab_Button_SignOut: value = "로그아웃"
        case .TiTiLab_Popup_SignOutTitle: value = "로그아웃하시겠어요?"
            
        case .SyncDaily_Text_InfoSync1: value = "현재 기기의 마지막 동기화 시간과 서버 내 반영된 최신 동기화 시간입니다."
        case .SyncDaily_Text_InfoSync2: value = "동기화를 통해 수정된 데이터가 백업되며 다른 기기에서 백업한 데이터를 받을 수 있습니다."
        case .SyncDaily_Text_InfoSync3: value = "서버 내 저장된 Dailys 개수와 현재 기기의 Dailys 개수입니다."
        case .SyncDaily_Text_InfoSync4: value = "동기화시 Created 와 Edited 정보들이 백업됩니다."
        case .SyncDaily_Button_SyncNow: value = "동기화"
        case .SyncDaily_Popup_InfoFirstSyncTitle: value = "첫 동기화 안내"
        case .SyncDaily_Popup_InfoFirstSyncDesc: value = "첫 동기화의 경우 모든 Daily 정보가 반영되기까지 오래걸릴 수 있으며(10s), 앱을 종료하지 말고 기다리시기 바랍니다."
            
        case .SwitchSetting_Button_Update: value = "업데이트"
        case .SwitchSetting_Button_5minNotiDesc: value = "종료 5분전 알림"
        case .SwitchSetting_Button_EndNotiDesc: value = "종료 알림"
        case .SwitchSetting_Button_1HourPassNotiDesc: value = "1시간단위 경과시 알림"
        case .SwitchSetting_Button_NewVerNotiDesc: value = "최신버전 업데이트 알림"
        case .SwitchSetting_Button_TimeAnimationTitle: value = "시간 변화 애니메이션"
        case .SwitchSetting_Button_TimeAnimationDesc: value = "시간 변화를 부드럽게 표시해요"
        case .SwitchSetting_Button_BigUITitle: value = "Big UI"
        case .SwitchSetting_Button_BigUIDesc: value = "아이패드용 Big UI 활성화"
        case .SwitchSetting_Button_KeepScreenOnTitle: value = "항상 화면 켜짐 유지"
        case .SwitchSetting_Button_KeepScreenOnDesc: value = "기록중에는 화면이 항상 켜진 상태로 유지됩니다"
        case .SwitchSetting_Button_FlipStartTitle: value = "뒤집어서 기록 시작"
        case .SwitchSetting_Button_FlipStartDesc: value = "기기를 뒤집으면 자동으로 기록이 시작됩니다"
            
        case .Language_Button_SystemLanguage: value = "System 언어"
        case .Language_Button_Korean: value = "한국어"
        case .Language_Button_English: value = "영어"
        case .Language_Button_Chinese: value = "중국어(간체)"
        case .Language_Popup_LanguageChangeTitle: value = "언어가 변경되었어요"
        case .Language_Popup_LanguageChangeDesc: value = "앱을 다시 실행해주세요"
            
        case .ColorSelector_Text_Color: value = "컬러"
        case .ColorSelector_Text_SetGraphColor: value = "그래프의 컬러를 설정합니다"
        case .ColorSelector_Text_SetWidgetColor: value = "위젯의 컬러를 설정합니다"
        case .ColorSelector_Text_ColorDirectionTitle: value = "컬러 방향"
        case .ColorSelector_Text_ColorDirectionDesc: value = "컬러 조합의 방향을 설정합니다"
            
        case .EmailMessage_Error_CantSendEmailTitle: value = "이메일 설정 실패"
        case .EmailMessage_Error_CantSendEmailDesc: value = "아이폰의 이메일 설정을 확인 후 다시 시도해주세요."
        case .EmailMessage_Text_Message: value = "작은 피드백 하나하나가 큰 도움이 됩니다 :)"
        case .EmailMessage_Text_FindNickname: value = "닉네임을 찾기 위한 가입한 이메일 정보가 필요합니다.\n\n가입한 이메일 :\n\n위 정보를 채워주셔서 전송 부탁드립니다."
            
        case .Recording_Text_TargetTime: value = "총 남은시간"
        case .Recording_Text_TaskTargetTime: value = "Task 남은시간"
        case .Recording_Text_SumTime: value = "누적 시간"
        case .Recording_Popup_NoTaskWarningTitle: value = "Task를 생성해주세요"
        case .Recording_Popup_NoTaskWarningDesc: value = "기록을 위해서 Task생성 후 선택해주세요"
        case .Recording_Popup_CheckDailyDateTitle: value = "기록중인 날짜를 확인해주세요"
        case .Recording_Popup_CheckDailyDateDesc: value = "새로운 날짜의 기록을 시작하시겠습니까?"
        case .Recording_Text_SetNewRecordTitle: value = "새로운 기록 설정"
        case .Recording_Text_SetDailyTargetTime: value = "목표시간 설정"
            
        case .Timer_Text_Finish: value = "종료"
        case .Timer_Text_TimerEndTime: value = "종료예정"
        case .Timer_Text_SetTimerTimeTitle: value = "타이머 시간 설정"
            
        case .Tasks_Hint_NewTaskTitle: value = "새로운 Task"
        case .Tasks_Popup_NewTaskDesc: value = "12자리 내의 새로운 Task명을 입력하세요"
        case .Tasks_Popup_EditTaskName: value = "Task명 수정"
        case .Tasks_Text_SetTaskTargetTime: value = "목표시간 설정"
        case .Tasks_Popup_SameTaskExistTitle: value = "동일한 Task 존재"
        case .Tasks_Popup_SameTaskExistDesc: value = "다른 Task명을 입력해주세요"
        case .Tasks_Popup_SetTaskTargetTime: value = "목표시간 설정"
            
        case .Todos_Popup_EditTodoName: value = "내용 수정"
        case .Todos_Hint_TodoName: value = "새로운 내용"
        case .Todos_Popup_EditTodoGroupName: value = "그룹명 수정"
        case .Todos_Hint_NewTodoGroupName: value = "새로운 그룹명"
        case .Todos_Button_CreateTodoGroup: value = "그룹 추가"
        case .Todos_Button_DeleteTodoGroup: value = "그룹 삭제"
        case .Todos_Popup_DeleteTodoGroupTitle: value = "{} 삭제"
        case .Todos_Popup_DeleteTodoGroupDesc: value = "{} 그룹을 삭제하시겠습니까?"
            
        case .EditDaily_Popup_UnableEditTitle: value = "기록 수정 불가"
        case .EditDaily_Popup_EditTaskName: value = "Task명 수정"
        case .EditDaily_Popup_EnterTaskName: value = "Task명 입력"
        case .EditDaily_Popup_EditTaskSaved: value = "변경 사항이 저장되었습니다."
        case .EditDaily_Popup_EditChangeCanceled: value = "변경 사항이 제거됩니다."
        case .EditDaily_Popup_SameTaskExist: value = "동일한 Task가 존재합니다."
        case .EditDaily_Popup_EditTaskNameDesc: value = "새로운 Task를 입력해주세요"
        case .EditDaily_Text_InfoEnterTaskName: value = "Task명을 입력해주세요"
        case .EditDaily_Text_StartAt: value = "시작 시각"
        case .EditDaily_Text_EndAt: value = "종료 시각"
        case .EditDaily_Text_InfoHowToEditDaily: value = "Task를 선택하여 기록수정 후\nSAVE를 눌러주세요"
        case .EditDaily_Text_InfoHowToCreateDaily: value = "\"+ 기록 추가\" 를 눌러 기록생성 후\nSAVE를 눌러주세요"
        case .EditDaily_Button_CreateNewTaskHistory: value = "Task 추가"
        case .EditDaily_Button_AppendNewHistory: value = "기록 추가"
        case .EditDaily_Popup_WatchADRequired: value = "저장하려면 광고를 시청해야 합니다. 광고를 시청하시겠습니까?"
        case .EditDaily_Popup_UndableEditDesc: value = "기록수정이 불가한 과거형식의 기록입니다. 업데이트를 기다려주세요"
            
        case .LogSetting_Text_DailyTargetTimeDesc: value = "원형 프로그래스바의 목표 시간을 설정합니다"
            
        case .RecordingColorSelector_Text_CustomColor: value = "커스텀 컬러"
        case .RecordingColorSelector_Text_BackgroundColor: value = "배경"
        case .RecordingColorSelector_Text_TextColor: value = "텍스트"
            
        case .SignIn_Text_TimerTiTi: value = "타이머티티"
        case .SignIn_Button_SocialSignIn: value = "{}로 로그인"
        case .SignIn_Button_WithoutSocialSingIn: value = "로그인없이 서비스 이용하기"
        case .SignIn_Hint_Email: value = "이메일"
        case .SignIn_Hint_Password: value = "비밀번호"
        case .SignIn_Button_TiTiSingIn: value = "로그인"
        case .SignIn_Text_OR: value = "또는"
        case .SignIn_Button_FindEmail: value = "이메일 찾기"
        case .SignIn_Button_FindPassword: value = "비밀번호 찾기"
        case .SignIn_Button_FindNickname: value = "닉네임 찾기"
        case .SignIn_Button_Contect: value = "문의하기"
        case .SignIn_Button_SignUp: value = "회원가입"
        case .SignIn_Error_SocialSignInFail: value = "로그인을 실패했어요"
        case .SignIn_Error_SocialSignInFailDomain: value = "{} 로그인을 확인해주세요"
        case .SignIn_Error_EmailSingInFail: value = "이메일과 비밀번호를 확인해주세요"
            
        case .SignIn_Error_AuthenticationError: value = "인증정보 오류"
        case .SignIn_Error_SigninFail: value = "로그인 실패"
        case .SignIn_Popup_SigninSuccess: value = "로그인 성공"
        case .SignIn_Error_SigninAgain: value = "다시 로그인해주세요"
        case .SignIn_Error_CheckNicknameOrPassword: value = "닉네임과 패스워드를 정확히 입력해주세요"
            
        case .SignUp_Text_InputEmailTitle: value = "이메일을 입력해 주세요"
        case .SignUp_Text_InputEmailDesc: value = "이메일 인증으로 본인을 확인해 주세요"
        case .SignUp_Hint_Email: value = "이메일"
        case .SignUp_Error_WrongEmailFormat: value = "잘못된 형식입니다. 올바른 형식으로 입력해 주세요"
        case .SignUp_Toast_SendCodeComplete: value = "인증코드가 발송되었습니다. 이메일을 확인해 주세요"
        case .SignUp_Hint_VerificationCode: value = "인증코드"
        case .SignUp_Button_Resend: value = "재전송"
        case .SignUp_Error_DuplicateEmail: value = "이미 사용 중인 이메일입니다. 다른 이메일을 입력해 주세요"
        case .SignUp_Error_WrongCode: value = "인증코드가 올바르지 않습니다. 다시 확인해 주세요"
        case .SignUp_Error_TooManySend: value = "인증코드 전송 시도가 너무 많습니다. 60분간 요청이 제한돼요"
        case .SignUp_Error_TooManyConfirm: value = "인증코드 확인 시도가 너무 많습니다. 10분간 요청이 제한돼요"
            
        case .SignUp_Text_InputPasswordTitle: value = "비밀번호를 입력해 주세요"
        case .SignUp_Text_InputPasswordDesc: value = "8자리 이상 비밀번호를 입력해 주세요 (영어, 숫자 포함)"
        case .SignUp_Hint_Password: value = "비밀번호"
        case .SignUp_Text_ConfirmPasswordDesc: value = "다시 한번 입력해 주세요"
        case .SignUp_Hint_ConfirmPassword: value = "비밀번호 재입력"
        case .SignUp_Error_PasswordFormat: value = "영문, 숫자를 포함하여 8자 이상 20자 이내로 입력해 주세요.\n특수문자는 !@#$%^&*()만 가능합니다"
        case .SignUp_Error_PasswordMismatch: value = "동일하지 않습니다. 다시 입력해 주세요"
            
        case .SignUp_Text_InputNicknameTitle: value = "닉네임을 입력해 주세요"
        case .SignUp_Text_InputNicknameDesc: value = "12자 이내로 닉네임을 입력해 주세요"
        case .SignUp_Hint_Nickname: value = "닉네임"
        case .SignUp_Error_WrongNicknameFormat: value = "2자 이상 12자 이내로 입력해 주세요.\n특수문자는 !@#$%^&*()만 가능합니다"
            
        case .SignUp_Error_SignupError: value = "회원가입 불가"
        case .SignUp_Popup_SignupSuccess: value = "회원가입 성공"
        case .SignUp_Error_EnterDifferentValue: value = "닉네임, 또는 이메일을 다른값으로 입력해주세요"
        case .SignUp_Error_CheckNicknameOrEmail: value = "닉네임 또는 이메일을 확인해주세요 (5자리 이상)"
            
        case .FindAccount_Text_InputNicknameDesc: value = "기존 계정의 닉네임을 입력해 주세요"
        case .FindAccount_Error_NotRegisteredNickname: value = "가입되지 않은 닉네임입니다"
        case .FindAccount_Text_InputEmailDesc: value = "기존 계정의 이메일을 입력해 주세요"
        case .FindAccount_Error_NotRegisteredEmail: value = "가입되지 않은 이메일입니다"
        case .FindAccount_Text_InputNewPasswordTitle: value = "새로운 비밀번호를 입력해 주세요"
        case .FindAccount_Error_NotRegisteredNicknameEmail: value = "닉네임과 이메일에 해당하는 유저가 존재하지 않습니다.\n다시 한 번 확인해 주세요"
        case .FindAccount_Text_ChangeCompletedTitle: value = "변경이 완료되었어요!"
        case .FindAccount_Text_ChangePasswordCompleted: value = "비밀번호가 재설정 되었어요!"
        case .FindAccount_Button_GoToLogin: value = "로그인하러 갈래요!"
            
        case .Server_Popup_ServerCantUseTitle: value = "서버를 일시적으로 사용할 수 없어요"
        case .Server_Popup_ServerCantUseDesc: value = "잠시 후 이용해 주세요 :)"
        case .Server_Error_NetworkError: value = "네트워크 오류"
        case .Server_Error_NetworkTimeout: value = "네트워크 시간초과"
        case .Server_Error_NetworkFetchError: value = "네트워크 수신불가"
        case .Server_Error_ServerError: value = "서버 오류"
        case .Server_Error_CheckNetwork: value = "네트워크를 확인 후 다시 시도해주세요"
        case .Server_Error_DecodeError: value = "최신 버전의 앱으로 업데이트를 해주세요"
        case .Server_Error_ServerErrorTryAgain: value = "서버에 오류가 발생했습니다. 잠시 후 다시 시도해주세요"
        case .Server_Error_UploadError: value = "업로드 오류"
        case .Server_Error_DownloadError: value = "다운로드 오류"
            
        case .Notification_Button_PassToday: value = "오늘 그만보기"
            
        case .WidgetSetting_Text_DailyTargetTimeDesc: value = "날짜별 누적 시간에 따른 색 농도표시를 위한 목표 시간을 설정합니다"
        case .WidgetSetting_Text_Description: value = "위젯 설명"
        case .WidgetSetting_Button_AddMethod: value = "위젯 추가 방법"
        case .WidgetSetting_Text_WidgetDesc1: value = "앱들이 흔들릴 때까지 홈 스크린의 빈 영역을 길게 눌러요"
        case .WidgetSetting_Text_WidgetDesc2: value = "상단 모서리에 있는 ( + ) 버튼을 터치해요"
        case .WidgetSetting_Text_WidgetDesc3: value = "\"TiTi\"를 검색한 후 터치해요"
        case .WidgetSetting_Text_WidgetDesc4: value = "위젯과 사이즈를 선택하고 \"위젯 추가\"를 터치해요"
        case .WidgetSetting_Text_WidgetDesc5: value = "그러면 위젯을 사용할 수 있어요!"
            
        case .Widget_Text_CalendarWidget: value = "캘린더 위젯"
        case .Widget_Text_CalendarWidgetDesc: value = "상위 5가지 Task와 날짜별 기록시간을 보여줍니다."
        case .Widget_Text_InfoNoRecords: value = "이번 달 기록이 없어요!"
        case .Widget_Text_SampleTask1: value = "국어"
        case .Widget_Text_SampleTask2: value = "수학"
        case .Widget_Text_SampleTask3: value = "영어"
        case .Widget_Text_SampleTask4: value = "한국사"
        case .Widget_Text_SampleTask5: value = "탐구"
        }
        
        if let op = op, value.contains("{}") {
            value = value.replacingOccurrences(of: "{}", with: "\(op)")
        }
        
        return value
    }
}
