//
//  TLRzh.swift
//  Project_Timer
//
//  Created by Kang Minsang on 2023/12/10.
//  Copyright © 2023 FDEE. All rights reserved.
//

import Foundation

struct TLRzh {
    static func value(key: TLRkey, op: String? = nil) -> String {
        var value: String = ""
        switch key {
        case .Common_Text_OK: value = "确认"
        case .Common_Text_Cencel: value = "取消"
        case .Common_Text_Edit: value = "编辑"
        case .Common_Text_Done: value = "完成"
        case .Common_Text_Next: value = "下一页"
        case .Common_Text_Close: value = "关闭"
        case .Common_Text_Delete: value = "删除"
        case .Common_Text_Back: value = "返回"
        case .Common_Text_Add: value = "添加"
        case .Common_Text_Timer: value = "计时器"
        case .Common_Text_Stopwatch: value = "秒表"
        case .Common_Text_TargetTime: value = "目标时间"
        case .Common_Popup_SetMonthTargetTime: value = "请输入 Month 的目标时间\n（以小时为单位）"
        case .Common_Popup_SetWeekTargetTime: value = "请输入 Week 的目标时间\n(以小时为单位)"
        case .Common_Popup_SetDailyTargetTime: value = "请输入 Daily 的目标时间\n(以小时为单位)"
        case .Common_Popup_SaveCompleted: value = "保存 完成"
        case .Common_Popup_Warning: value = "警告"
        case .Common_Popup_Inform: value = "向导"
            
        case .System_Noti_StopwatchHourPassed: value = "{}时间已过。"
        case .System_Noti_TimerFinished: value = "计时器已结束 ！"
        case .System_Noti_Timer5Left: value = "还剩5分钟"
        case .System_Noti_RecordingStart: value = "记录开始了"
            
        case .Update_Popup_HardUpdateTitle: value = "需要更新"
        case .Update_Popup_HardUpdateDesc: value = "请更新到最新版本"
        case .Update_Pupup_SoftUpdateTitle: value = "新版本发布"
        case .Update_Popup_SoftUpdateDesc: value = "{} 请使用版本"
        case .Update_Popup_Update: value = "更新"
        case .Update_Popup_NotNow: value = "不是现在"
            
        case .Settings_Text_ProfileSection: value = "個人資料"
        case .Settings_Button_SingInOption: value = "登录"
        case .Settings_Button_SingInOptionDesc: value = "尝试同步"
        case .Settings_Text_ServiceSection: value = "服务"
        case .Settings_Button_Functions: value = "功能"
        case .Settings_Button_TiTiLab: value = "TiTi实验室"
        case .Settings_Text_SettingSection: value = "设置"
        case .Settings_Button_Notification: value = "通知"
        case .Settings_Button_UI: value = "用户界面"
        case .Settings_Button_Control: value = "控制"
        case .Settings_Button_LanguageOption: value = "语言"
        case .Settings_Button_Widget: value = "小部件"
        case .Settings_Text_VersionSection: value = "版本和更新历史"
        case .Settings_Button_VersionInfoTitle: value = "版本信息"
        case .Settings_Button_VersionInfoDesc: value = "最新版本"
        case .Settings_Button_UpdateHistory: value = "更新细目"
        case .Settings_Text_BackupSection: value = "备份"
        case .Settings_Button_GetBackup: value = "获取备份文件"
        case .Settings_Text_DeveloperSection: value = "开发团队"
            
        case .TiTiLab_Text_DevelopNews: value = "开发新闻"
        case .TiTiLab_Button_InstagramDesc: value = "通过Instagram查看各种开发消息"
        case .TiTiLab_Text_PartInDev: value = "参与TiTi开发"
        case .TiTiLab_Text_SurveyTitle: value = "调查问卷"
        case .TiTiLab_Text_SurveyDesc: value = "实时显示新的调查。\n参与新功能的开发和改进。"
        case .TiTiLab_Text_NoServey: value = "目前没有正在进行的问卷调查。"
        case .TiTiLab_Text_Sync: value = "同步"
        case .TiTiLab_Button_SignUpTitle: value = "注册会员"
        case .TiTiLab_Button_SignUpDesc: value = "Dailys 记录同步 (beta)"
        case .TiTiLab_Button_SignIn: value = "登录"
        case .TiTiLab_Button_SignOut: value = "退出登录"
        case .TiTiLab_Popup_SignOutTitle: value = "您要退出吗?"
            
        case .SyncDaily_Text_InfoSync1: value = "当前设备的最后同步时间以及服务器上反映的最新同步时间 。"
        case .SyncDaily_Text_InfoSync2: value = "通过同步对修改后的数据进行备份，可接收其他设备备份的数据。"
        case .SyncDaily_Text_InfoSync3: value = "服务器内保存的Dailys数量和当前设备的Dailys数量。"
        case .SyncDaily_Text_InfoSync4: value = "同步时备份Created和Edited信息。"
        case .SyncDaily_Button_SyncNow: value = "同步"
        case .SyncDaily_Popup_InfoFirstSyncTitle: value = "第一次同步通知"
        case .SyncDaily_Popup_InfoFirstSyncDesc: value = "首次同步可能需要很长时间才能反映所有Daily信息（10s），请不要关闭应用程序，等待。"
            
        case .SwitchSetting_Button_Update: value = "更新"
        case .SwitchSetting_Button_5minNotiDesc: value = "结束前5分钟提醒"
        case .SwitchSetting_Button_EndNotiDesc: value = "结束"
        case .SwitchSetting_Button_1HourPassNotiDesc: value = "每隔1小时提醒"
        case .SwitchSetting_Button_NewVerNotiDesc: value = "新版本弹出警报"
        case .SwitchSetting_Button_TimeAnimationTitle: value = "时间变化动画"
        case .SwitchSetting_Button_TimeAnimationDesc: value = "平滑显示时间变化"
        case .SwitchSetting_Button_BigUITitle: value = "大型用户界面"
        case .SwitchSetting_Button_BigUIDesc: value = "为 iPad 使用 Big UI"
        case .SwitchSetting_Button_KeepScreenOnTitle: value = "始终保持屏幕打开"
        case .SwitchSetting_Button_KeepScreenOnDesc: value = "在录制过程中保持屏幕打开"
        case .SwitchSetting_Button_FlipStartTitle: value = "翻转开始录制"
        case .SwitchSetting_Button_FlipStartDesc: value = "翻转机器后自动开始记录"
            
        case .Language_Button_SystemLanguage: value = "System 语言"
        case .Language_Button_Korean: value = "韩语"
        case .Language_Button_English: value = "英语"
        case .Language_Button_Chinese: value = "简体中文"
        case .Language_Popup_LanguageChangeTitle: value = "语言已更改"
        case .Language_Popup_LanguageChangeDesc: value = "请重启APP"
            
        case .ColorSelector_Text_Color: value = "颜色"
        case .ColorSelector_Text_SetGraphColor: value = "设置图表的颜色"
        case .ColorSelector_Text_SetWidgetColor: value = "配置部件的颜色"
        case .ColorSelector_Text_ColorDirectionTitle: value = "颜色方向"
        case .ColorSelector_Text_ColorDirectionDesc: value = "设置颜色组合的方向"
            
        case .EmailMessage_Error_CantSendEmailTitle: value = "电子邮件设置失败"
        case .EmailMessage_Error_CantSendEmailDesc: value = "请确认苹果手机的电子邮件设置后再试一次。"
        case .EmailMessage_Text_Message: value = "每一个小小的反馈都有很大的帮助 :)"
        case .EmailMessage_Text_FindNickname: value = "我需要您注册的电子邮件信息来查找您的昵称。\n\n注册邮箱: \n\n请填写以上信息并发送给我们"
            
        case .Recording_Text_TargetTime: value = "目标时间"
        case .Recording_Text_TaskTargetTime: value = "Task 目标时间"
        case .Recording_Text_SumTime: value = "总时间"
        case .Recording_Popup_NoTaskWarningTitle: value = "创建新任务"
        case .Recording_Popup_NoTaskWarningDesc: value = "在开始录制之前，创建新任务，然后选择"
        case .Recording_Popup_CheckDailyDateTitle: value = "请确认记录中的日期。"
        case .Recording_Popup_CheckDailyDateDesc: value = "开始记录新日期吗 ？"
        case .Recording_Text_SetNewRecordTitle: value = "新建日志设置"
        case .Recording_Text_SetDailyTargetTime: value = "设定目标时间"
            
        case .Timer_Text_Finish: value = "结束"
        case .Timer_Text_TimerEndTime: value = "结束时间"
        case .Timer_Text_SetTimerTimeTitle: value = "定时器时间设置"
            
        case .Tasks_Hint_NewTaskTitle: value = "新 Task"
        case .Tasks_Popup_NewTaskDesc: value = "Task名称的最大长度为 20"
        case .Tasks_Popup_EditTaskName: value = "修改 Task 名称"
        case .Tasks_Text_SetTaskTargetTime: value = "设定目标时间"
        case .Tasks_Popup_SameTaskExistTitle: value = "相同的 Task 存在"
        case .Tasks_Popup_SameTaskExistDesc: value = "请输入其他Task名"
        case .Tasks_Popup_SetTaskTargetTime: value = "设定目标时间"
            
        case .Todos_Popup_EditTodoName: value = "修改内容"
        case .Todos_Hint_TodoName: value = "新建内容"
        case .Todos_Popup_EditTodoGroupName: value = "修改组名"
        case .Todos_Hint_NewTodoGroupName: value = "新建组名"
        case .Todos_Button_CreateTodoGroup: value = "添加组"
        case .Todos_Button_DeleteTodoGroup: value = "删除组"
        case .Todos_Popup_DeleteTodoGroupTitle: value = "删除{}"
        case .Todos_Popup_DeleteTodoGroupDesc: value = "您是否要删除{}群组？"
            
        case .EditDaily_Popup_UnableEditTitle: value = "无法修改历史"
        case .EditDaily_Popup_EditTaskName: value = "修改 Task 名称"
        case .EditDaily_Popup_EnterTaskName: value = "输入 Task 名"
        case .EditDaily_Popup_EditTaskSaved: value = "已保存变更事项。"
        case .EditDaily_Popup_EditChangeCanceled: value = "变更事项将被删除。"
        case .EditDaily_Popup_SameTaskExist: value = "存在相同的 Task。"
        case .EditDaily_Popup_EditTaskNameDesc: value = "请输入新的 Task"
        case .EditDaily_Text_InfoEnterTaskName: value = "请输入 Task名"
        case .EditDaily_Text_StartAt: value = "起始时刻"
        case .EditDaily_Text_EndAt: value = "结束时刻"
        case .EditDaily_Text_InfoHowToEditDaily: value = "选择 Task 修改记录后\n请按 SAVE"
        case .EditDaily_Text_InfoHowToCreateDaily: value = "点击\"+ 新 Task\"，创建记录\n并按 SAVE"
        case .EditDaily_Button_CreateNewTaskHistory: value = "新 Task"
        case .EditDaily_Button_AppendNewHistory: value = "新建记录"
        case .EditDaily_Popup_WatchADRequired: value = "保存需要观看广告。 确定要收看广告吗？"
        case .EditDaily_Popup_UndableEditDesc: value = "记录不能修改的过去格式的记录。 请等待更新。"
            
        case .LogSetting_Text_DailyTargetTimeDesc: value = "设置圆形程序栏的目标时间"
            
        case .RecordingColorSelector_Text_CustomColor: value = "定制颜色"
        case .RecordingColorSelector_Text_BackgroundColor: value = "后台"
        case .RecordingColorSelector_Text_TextColor: value = "文本"
            
        case .SignIn_Text_TimerTiTi: value = "TimerTiTi"
        case .SignIn_Button_SocialSignIn: value = "使用 {} 登录"
        case .SignIn_Button_WithoutSocialSingIn: value = "无需登录即可使用"
        case .SignIn_Hint_Email: value = "电子邮件"
        case .SignIn_Hint_Password: value = "密码 "
        case .SignIn_Button_TiTiSingIn: value = "登录"
        case .SignIn_Text_OR: value = "或者"
        case .SignIn_Button_FindEmail: value = "忘记电子邮件?"
        case .SignIn_Button_FindPassword: value = "忘记密码?"
        case .SignIn_Button_FindNickname: value = "忘记昵称?"
        case .SignIn_Button_Contect: value = "联系我们"
        case .SignIn_Button_SignUp: value = "注册会员"
        case .SignIn_Error_SocialSignInFail: value = "登录失败"
        case .SignIn_Error_SocialSignInFailDomain: value = "请检查您的 {} 登录"
        case .SignIn_Error_EmailSingInFail: value = "请检查您的电子邮件和密码"
            
        case .SignIn_Error_AuthenticationError: value = "验证错误"
        case .SignIn_Error_SigninFail: value = "登录失败"
        case .SignIn_Popup_SigninSuccess: value = "登录成功"
        case .SignIn_Error_SigninAgain: value = "请重新登录"
        case .SignIn_Error_CheckNicknameOrPassword: value = "请正确输入您的昵称和密码"
            
        case .SignUp_Text_InputEmailTitle: value = "请输入您的电子邮件地址"
        case .SignUp_Text_InputEmailDesc: value = "我们需要您的电子邮件进行验证"
        case .SignUp_Hint_Email: value = "电子邮件"
        case .SignUp_Error_WrongEmailFormat: value = "无效的格式。 请输入正确的格式"
        case .SignUp_Toast_SendCodeComplete: value = "验证码已发送。 请检查您的电子邮件"
        case .SignUp_Hint_VerificationCode: value = "验证码"
        case .SignUp_Button_Resend: value = "重新发送"
        case .SignUp_Error_DuplicateEmail: value = "此电子邮件已在使用中。 请输入另一个"
        case .SignUp_Error_WrongCode: value = "验证码错误。 请再次检查"
        case .SignUp_Error_TooManySend: value = "太多的尝试。 请求被限制为60分钟"
        case .SignUp_Error_TooManyConfirm: value = "太多的尝试。 请求限制为10分钟"
            
        case .SignUp_Text_InputPasswordTitle: value = "请创建新密码"
        case .SignUp_Text_InputPasswordDesc: value = "密码必须是8个或更多字符（包括英文和数字）"
        case .SignUp_Hint_Password: value = "密码"
        case .SignUp_Text_ConfirmPasswordDesc: value = "请再次输入"
        case .SignUp_Hint_ConfirmPassword: value = "确认您的密码"
        case .SignUp_Error_PasswordFormat: value = "密码应为8~20个字符，包括英语和数字。\n特殊字符被模仿 !@#$%^&*() 仅限"
        case .SignUp_Error_PasswordMismatch: value = "不一样。 请重新输入"
            
        case .SignUp_Text_InputNicknameTitle: value = "请创建您的昵称"
        case .SignUp_Text_InputNicknameDesc: value = "昵称应为12个字符或更少"
        case .SignUp_Hint_Nickname: value = "昵称"
        case .SignUp_Error_WrongNicknameFormat: value = "昵称应该是2~12个字符。\n特殊字符被模仿 !@#$%^&*() 仅限"
            
        case .SignUp_Error_SignupError: value = "注册错误"
        case .SignUp_Popup_SignupSuccess: value = "注册成功"
        case .SignUp_Error_EnterDifferentValue: value = "请输入您的昵称或电子邮件为不同的值"
        case .SignUp_Error_CheckNicknameOrEmail: value = "请检查您的昵称或电子邮件（至少5个字符)"
            
        case .FindAccount_Text_InputNicknameDesc: value = "请输入注册账户的昵称"
        case .FindAccount_Error_NotRegisteredNickname: value = "此昵称未注册"
        case .FindAccount_Text_InputEmailDesc: value = "请输入注册账户的电子邮件"
        case .FindAccount_Error_NotRegisteredEmail: value = "此电子邮件未注册"
        case .FindAccount_Text_InputNewPasswordTitle: value = "请输入新密码"
        case .FindAccount_Error_NotRegisteredNicknameEmail: value = "对应于昵称和电子邮件的用户不存在。\n请再次检查"
        case .FindAccount_Text_ChangeCompletedTitle: value = "变更已完成！"
        case .FindAccount_Text_ChangePasswordCompleted: value = "密码已更改！"
        case .FindAccount_Button_GoToLogin: value = "去登录"
            
        case .Server_Popup_ServerCantUseTitle: value = "暂时无法使用服务器"
        case .Server_Popup_ServerCantUseDesc: value = "请稍后使用 :)"
        case .Server_Error_NetworkError: value = "网络错误"
        case .Server_Error_NetworkTimeout: value = "网络超时"
        case .Server_Error_NetworkFetchError: value = "网络获取错误"
        case .Server_Error_ServerError: value = "服务器错误"
        case .Server_Error_CheckNetwork: value = "请检查网络并重试"
        case .Server_Error_DecodeError: value = "请更新到最新版本的应用程序"
        case .Server_Error_ServerErrorTryAgain: value = "服务器出错啦! 请稍后再试。"
        case .Server_Error_UploadError: value = "上传错误"
        case .Server_Error_DownloadError: value = "下载错误"
            
        case .Notification_Button_PassToday: value = "今日不再显示"
            
        case .WidgetSetting_Text_DailyTargetTimeDesc: value = "根据日期的总时间设置颜色密度显示的目标时间"
        case .WidgetSetting_Text_Description: value = "关于小部件"
        case .WidgetSetting_Button_AddMethod: value = "如何添加小部件"
        case .WidgetSetting_Text_WidgetDesc1: value = "触摸并按住主屏幕上的空区域,直到应用程序抖动。"
        case .WidgetSetting_Text_WidgetDesc2: value = "点击上角的 ( + ) 按钮。"
        case .WidgetSetting_Text_WidgetDesc3: value = "搜索\"TiTi\"后点击。"
        case .WidgetSetting_Text_WidgetDesc4: value = "选择一个小部件和大小，然后轻按\"添加小部件\"。"
        case .WidgetSetting_Text_WidgetDesc5: value = "现在你可以使用小部件了！"
            
        case .Widget_Text_CalendarWidget: value = "日历小部件"
        case .Widget_Text_CalendarWidgetDesc: value = "小部件显示前5项任务和按日期记录的时间。"
        case .Widget_Text_InfoNoRecords: value = "这个月没有记录！"
        case .Widget_Text_SampleTask1: value = "英语"
        case .Widget_Text_SampleTask2: value = "数学"
        case .Widget_Text_SampleTask3: value = "物理"
        case .Widget_Text_SampleTask4: value = "化学"
        case .Widget_Text_SampleTask5: value = "生物"
            
        case .Toast_Text_NewRecord: value = "开始录制!"
        }
        
        if let op = op, value.contains("{}") {
            value = value.replacingOccurrences(of: "{}", with: "\(op)")
        }
        
        return value
    }
}
